include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - /**/*.g.dart

linter:
  rules:
    avoid_redundant_argument_values: true
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_relative_imports: true
    use_build_context_synchronously: true
